COMMON: &common
  SECRET_KEY: insecure1
  SECURITY_POST_LOGIN_VIEW: '/profile'

  ADMIN_CREDENTIALS: 'admin,password'

  SECURITY_TRACKABLE: True
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'
  SOCIAL_APP_URL: http://flask-social-example.herokuapp.com/
  URL: http://flask-social-example.herokuapp.com/

DEVELOPMENT: &development
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'postgresql://postgres@localhost:5432/gisdev'
  DEBUG: True

PRODUCTION: &production
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'postgresql://postgres@localhost:5432/gis'
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://flask-social-example.herokuapp.com/
