
DEVELOPMENT:
  SOCIAL_TWITTER:
    consumer_key: 'el3QsXJ5TETmjViiKSHsQ'
    consumer_secret: 'PSedh7CSDlo4Bsy5DPV5eEEn4456lEqtZRChft1YG0'

  SOCIAL_FACEBOOK:
    consumer_key: '133152743541814'
    consumer_secret: '7cef894a32184889f2c37129b707edb6'
    request_token_params:
      scope: 'email,'

  SOCIAL_GITHUB:
    consumer_key: '05f3bf6d26ec30ed42aa'
    consumer_secret: '966c8cd455e69d2da39369ca7e4fb45018262319'
    module: 'app.github'
    request_token_params:
      scope: 'user'

PRODUCTION:
  SECRET_KEY: somethingsecret
  GOOGLE_ANALYTICS_ID: your_GA_id

  SOCIAL_TWITTER:
    consumer_key: 'el3QsXJ5TETmjViiKSHsQ'
    consumer_secret: 'PSedh7CSDlo4Bsy5DPV5eEEn4456lEqtZRChft1YG0'

  SOCIAL_FACEBOOK:
    consumer_key: '133152743541814'
    consumer_secret: '7cef894a32184889f2c37129b707edb6'
    request_token_params:
      scope: 'email,publish_stream'

  SOCIAL_GITHUB:
    consumer_key: '05f3bf6d26ec30ed42aa'
    consumer_secret: '966c8cd455e69d2da39369ca7e4fb45018262319'
    module: 'app.github'
    request_token_params:
      scope: 'user'
